name = "keep-li-api"
main = "src/index.ts"
compatibility_date = "2024-09-30"

[vars]
API_VERSION = "v1"

[[kv_namespaces]]
binding = "USAGE_KV"
id = ""

[[kv_namespaces]]
binding = "FLAGS_KV"
id = ""
