name = "keep-li-api"
main = "src/index.ts"
compatibility_date = "2024-09-30"

[vars]
API_VERSION = "v1"

[[kv_namespaces]]
binding = "KV"
id = "your_kv_namespace_id_here"
preview_id = "your_preview_kv_namespace_id_here"

# Secrets should be set via: wrangler secret put <KEY>
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# SENTRY_DSN
